Traceback (most recent call last):
  File "/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: code signature in (/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dxf12_outlines.py", line 29, in <module>
    from inkex.bezier import cspsubdiv
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/bezier.py", line 29, in <module>
    import numpy
  File "/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "/Applications/Inkscape.app/Contents/Resources/bin/python3",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so, 2): no suitable image found.  Did find:
	/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so: code signature in (/Users/blairsubbaraman/Library/Python/3.8/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

